apiVersion: v2
name: sd-factoring
description: "BIAN Service Domain: Factoring (Fulfill pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - fulfill
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Trade Banking"
  bian/asset-type: "Factoring Facility"
  bian/control-record: "Factoring Facility Fulfillment Arrangement"
